#!/usr/bin/env python3
"""Extract a bounded, timestamped YouTube transcript into an ephemeral workspace."""

from __future__ import annotations

import argparse
import contextlib
import hashlib
import html
import inspect
import json
import re
import tempfile
from collections.abc import Iterable, Iterator, Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any
from xml.etree import ElementTree

VIDEO_URL = re.compile(r"^https://www\.youtube\.com/watch\?v=[A-Za-z0-9_-]{11}$")
CLIENTS = ("WEB", "ANDROID", "IOS")
ZERO_WIDTH = re.compile("[\u200b-\u200f\u2060\ufeff]")


class TranscriptUnavailable(RuntimeError):
    """Terminal bounded outcome when captions cannot be obtained without credentials."""

    reason_code = "youtube_transcript_unavailable"


@dataclass(frozen=True, slots=True)
class CaptionChoice:
    """Normalized caption identity used for deterministic preference ordering."""

    caption: object
    language_code: str
    name: str
    autogenerated: bool


@dataclass(frozen=True, slots=True)
class TranscriptSegment:
    """One canonical timestamped caption segment."""

    start_ms: int
    end_ms: int
    text: str


@dataclass(frozen=True, slots=True)
class TranscriptDocument:
    """Canonical transcript plus access provenance that is never persisted in the repository."""

    video_url: str
    language_code: str
    caption_name: str
    autogenerated: bool
    attempt: int
    client: str
    transcript_hash: str
    segments: tuple[TranscriptSegment, ...]


def _text(value: object) -> str:
    if isinstance(value, str):
        return value
    if isinstance(value, Mapping):
        simple = value.get("simpleText")
        if isinstance(simple, str):
            return simple
        runs = value.get("runs")
        if isinstance(runs, list):
            return "".join(str(run.get("text", "")) for run in runs if isinstance(run, Mapping))
    return str(value or "")


def _caption_choice(caption: object) -> CaptionChoice:
    raw_language_code = str(getattr(caption, "code", "") or getattr(caption, "language_code", ""))
    name = _text(getattr(caption, "name", ""))
    raw_generated = getattr(caption, "is_generated", None)
    autogenerated = (
        raw_language_code.startswith("a.")
        or bool(raw_generated)
        or any(
            marker in name.casefold()
            for marker in ("auto-generated", "automatically generated", "automatic")
        )
    )
    language_code = raw_language_code.removeprefix("a.").removeprefix(".")
    return CaptionChoice(caption, language_code, name, autogenerated)


def select_caption(
    captions: Iterable[object],
    languages: Sequence[str],
    *,
    prefer_human: bool = True,
) -> CaptionChoice | None:
    """Choose human English by language order, then auto-generated English."""

    choices = tuple(_caption_choice(caption) for caption in captions)
    generation_order = (False, True) if prefer_human else (True, False)
    for autogenerated in generation_order:
        for language in languages:
            exact = next(
                (
                    choice
                    for choice in choices
                    if choice.language_code == language and choice.autogenerated is autogenerated
                ),
                None,
            )
            if exact is not None:
                return exact
        for language in languages:
            base = language.split("-", maxsplit=1)[0]
            fallback = next(
                (
                    choice
                    for choice in choices
                    if choice.language_code.split("-", maxsplit=1)[0] == base
                    and choice.autogenerated is autogenerated
                ),
                None,
            )
            if fallback is not None:
                return fallback
    return None


def _normalized_text(value: str) -> str:
    decoded = html.unescape(value).replace("\r", " ").replace("\n", " ")
    return " ".join(ZERO_WIDTH.sub("", decoded).split())


def normalize_caption_events(
    events: Iterable[Mapping[str, object]],
) -> tuple[TranscriptSegment, ...]:
    """Normalize pytubefix caption JSON into stable ordered millisecond segments."""

    parsed: list[tuple[int, int, int, str]] = []
    for index, event in enumerate(events):
        raw_start = event.get("tStartMs", event.get("start_ms", event.get("start", 0)))
        raw_duration = event.get("dDurationMs", event.get("duration_ms", event.get("duration", 0)))
        try:
            start_ms = int(float(str(raw_start)))
            duration_ms = int(float(str(raw_duration)))
        except ValueError:
            continue
        segments = event.get("segs")
        if isinstance(segments, list):
            raw_text = "".join(
                str(segment.get("utf8", "")) for segment in segments if isinstance(segment, Mapping)
            )
        else:
            raw_text = str(event.get("text", ""))
        text = _normalized_text(raw_text)
        if start_ms < 0 or not text:
            continue
        end_ms = start_ms + max(duration_ms, 0)
        parsed.append((start_ms, end_ms, index, text))
    output: list[TranscriptSegment] = []
    for start_ms, end_ms, _, text in sorted(parsed):
        segment = TranscriptSegment(start_ms=start_ms, end_ms=end_ms, text=text)
        if output and output[-1] == segment:
            continue
        output.append(segment)
    return tuple(output)


def _xml_events(value: str) -> list[dict[str, object]]:
    root = ElementTree.fromstring(value)
    events: list[dict[str, object]] = []
    for node in root.findall(".//text"):
        start_ms = round(float(node.attrib.get("start", "0")) * 1000)
        duration_ms = round(float(node.attrib.get("dur", "0")) * 1000)
        events.append(
            {
                "tStartMs": start_ms,
                "dDurationMs": duration_ms,
                "text": "".join(node.itertext()),
            }
        )
    return events


def _caption_events(caption: object) -> Iterable[Mapping[str, object]]:
    raw_json = getattr(caption, "json_captions", None)
    if isinstance(raw_json, Mapping):
        events = raw_json.get("events", [])
        if isinstance(events, list):
            return tuple(event for event in events if isinstance(event, Mapping))
    raw_xml = getattr(caption, "xml_captions", None)
    if isinstance(raw_xml, str) and raw_xml.strip():
        return _xml_events(raw_xml)
    return ()


def canonical_transcript(segments: Sequence[TranscriptSegment]) -> str:
    """Serialize segments for hashing without SRT formatting ambiguity."""

    return (
        "\n".join(f"{segment.start_ms}\t{segment.end_ms}\t{segment.text}" for segment in segments)
        + "\n"
    )


def transcript_hash(segments: Sequence[TranscriptSegment]) -> str:
    return hashlib.sha256(canonical_transcript(segments).encode("utf-8")).hexdigest()


def _all_captions(query: object) -> tuple[object, ...]:
    all_method = getattr(query, "all", None)
    if callable(all_method):
        value = all_method()
        if isinstance(value, list):
            return tuple(value)
    try:
        return tuple(query)  # type: ignore[arg-type]
    except TypeError:
        return ()


def _youtube(video_url: str, client: str) -> object:
    from pytubefix import YouTube

    parameters = inspect.signature(YouTube).parameters
    kwargs: dict[str, object] = {}
    if "client" in parameters:
        kwargs["client"] = client
    if "use_oauth" in parameters:
        kwargs["use_oauth"] = False
    if "allow_oauth_cache" in parameters:
        kwargs["allow_oauth_cache"] = False
    return YouTube(video_url, **kwargs)


def extract_transcript(
    video_url: str,
    languages: Sequence[str],
    *,
    prefer_human: bool = True,
    attempts: int = 3,
    youtube_factory: Any = _youtube,
) -> TranscriptDocument:
    """Make bounded anonymous caption attempts and return a canonical transcript."""

    if not VIDEO_URL.fullmatch(video_url):
        raise ValueError("video_url must be a canonical YouTube watch URL")
    if attempts < 1 or attempts > len(CLIENTS):
        raise ValueError(f"attempts must be between 1 and {len(CLIENTS)}")
    if not languages:
        raise ValueError("at least one transcript language is required")
    failures: list[str] = []
    for attempt, client in enumerate(CLIENTS[:attempts], start=1):
        try:
            youtube = youtube_factory(video_url, client)
            choice = select_caption(
                _all_captions(getattr(youtube, "captions", ())),
                languages,
                prefer_human=prefer_human,
            )
            if choice is None:
                raise TranscriptUnavailable("no preferred caption track")
            segments = normalize_caption_events(_caption_events(choice.caption))
            if not segments:
                raise TranscriptUnavailable("selected caption track is empty")
            return TranscriptDocument(
                video_url=video_url,
                language_code=choice.language_code,
                caption_name=choice.name,
                autogenerated=choice.autogenerated,
                attempt=attempt,
                client=client,
                transcript_hash=transcript_hash(segments),
                segments=segments,
            )
        except Exception as exc:  # Each anonymous client is an independent bounded attempt.
            failures.append(f"{client}:{exc.__class__.__name__}")
    raise TranscriptUnavailable(
        f"{TranscriptUnavailable.reason_code}; attempts={attempts}; clients={','.join(failures)}"
    )


def _timestamp(milliseconds: int) -> str:
    hours, remainder = divmod(milliseconds, 3_600_000)
    minutes, remainder = divmod(remainder, 60_000)
    seconds, millis = divmod(remainder, 1000)
    return f"{hours:02d}:{minutes:02d}:{seconds:02d}.{millis:03d}"


def chunk_segments(
    segments: Sequence[TranscriptSegment], *, maximum_characters: int
) -> tuple[tuple[TranscriptSegment, ...], ...]:
    """Partition every segment into deterministic bounded chunks without omission."""

    if maximum_characters < 500:
        raise ValueError("maximum_characters must be at least 500")
    chunks: list[tuple[TranscriptSegment, ...]] = []
    current: list[TranscriptSegment] = []
    current_size = 0
    for segment in segments:
        rendered_size = len(segment.text) + 40
        if rendered_size > maximum_characters:
            raise ValueError("one transcript segment exceeds the chunk bound")
        if current and current_size + rendered_size > maximum_characters:
            chunks.append(tuple(current))
            current = []
            current_size = 0
        current.append(segment)
        current_size += rendered_size
    if current:
        chunks.append(tuple(current))
    return tuple(chunks)


@contextlib.contextmanager
def transcript_workspace(
    document: TranscriptDocument,
    *,
    maximum_chunk_characters: int = 12_000,
) -> Iterator[tuple[Path, tuple[Path, ...]]]:
    """Yield JSON chunks in a temporary directory and remove all transcript bytes on exit."""

    with tempfile.TemporaryDirectory(prefix="papertrader-youtube-") as raw_directory:
        directory = Path(raw_directory)
        paths: list[Path] = []
        for index, chunk in enumerate(
            chunk_segments(document.segments, maximum_characters=maximum_chunk_characters),
            start=1,
        ):
            path = directory / f"chunk-{index:04d}.json"
            path.write_text(
                json.dumps(
                    {
                        "chunk_index": index,
                        "video_url": document.video_url,
                        "transcript_hash": document.transcript_hash,
                        "start": _timestamp(chunk[0].start_ms),
                        "end": _timestamp(chunk[-1].end_ms),
                        "segments": [
                            {
                                "start": _timestamp(segment.start_ms),
                                "end": _timestamp(segment.end_ms),
                                "text": segment.text,
                            }
                            for segment in chunk
                        ],
                    },
                    ensure_ascii=False,
                    sort_keys=True,
                    separators=(",", ":"),
                )
                + "\n",
                encoding="utf-8",
            )
            paths.append(path)
        yield directory, tuple(paths)


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser()
    parser.add_argument("--video-url", required=True)
    parser.add_argument("--languages", default="en,en-US,en-GB")
    parser.add_argument("--attempts", type=int, default=3)
    parser.add_argument("--prefer-auto", action="store_true")
    parser.add_argument("--chunk-characters", type=int, default=12_000)
    return parser


def main() -> int:
    arguments = _parser().parse_args()
    languages = tuple(value.strip() for value in arguments.languages.split(",") if value.strip())
    try:
        document = extract_transcript(
            arguments.video_url,
            languages,
            prefer_human=not arguments.prefer_auto,
            attempts=arguments.attempts,
        )
        with transcript_workspace(
            document, maximum_chunk_characters=arguments.chunk_characters
        ) as (_, paths):
            chunks = [json.loads(path.read_text(encoding="utf-8")) for path in paths]
            print(
                json.dumps(
                    {
                        "status": "available",
                        "language_code": document.language_code,
                        "caption_name": document.caption_name,
                        "autogenerated": document.autogenerated,
                        "attempt": document.attempt,
                        "client": document.client,
                        "transcript_hash": document.transcript_hash,
                        "chunk_count": len(chunks),
                        "chunks": chunks,
                    },
                    ensure_ascii=False,
                    sort_keys=True,
                )
            )
        return 0
    except TranscriptUnavailable as exc:
        print(
            json.dumps(
                {
                    "status": "unavailable",
                    "reason_code": TranscriptUnavailable.reason_code,
                    "detail": str(exc),
                },
                sort_keys=True,
            )
        )
        return 3


if __name__ == "__main__":
    raise SystemExit(main())
