from __future__ import annotations

import importlib.util
import sys
from pathlib import Path
from types import ModuleType

import pytest


def _module(repository_root: Path) -> ModuleType:
    path = (
        repository_root / "skills" / "papertrader-wiki-ingest" / "scripts" / "youtube_transcript.py"
    )
    spec = importlib.util.spec_from_file_location("papertrader_youtube_transcript", path)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


class Caption:
    def __init__(self, code: str, name: str, events: list[dict[str, object]]) -> None:
        self.code = code
        self.name = name
        self.json_captions = {"events": events}


class Captions:
    def __init__(self, values: list[Caption]) -> None:
        self.values = values

    def all(self) -> list[Caption]:
        return self.values


class Video:
    def __init__(self, captions: list[Caption]) -> None:
        self.captions = Captions(captions)


def test_human_english_precedes_auto_generated_and_language_fallback(
    repository_root: Path,
) -> None:
    module = _module(repository_root)
    auto = Caption("a.en", "English (auto-generated)", [])
    human = Caption("en-GB", "English (United Kingdom)", [])

    selected = module.select_caption([auto, human], ["en", "en-GB"], prefer_human=True)

    assert selected.caption is human
    assert selected.autogenerated is False


def test_timestamp_normalization_hashing_and_ephemeral_bounded_chunks(
    repository_root: Path,
) -> None:
    module = _module(repository_root)
    segments = module.normalize_caption_events(
        [
            {"tStartMs": "1000", "dDurationMs": "900", "segs": [{"utf8": " Alpha\n beta "}]},
            {"tStartMs": "2500", "dDurationMs": "500", "segs": [{"utf8": "Gamma &amp; delta"}]},
        ]
    )
    digest = module.transcript_hash(segments)
    document = module.TranscriptDocument(
        video_url="https://www.youtube.com/watch?v=abcdefghijk",
        language_code="en",
        caption_name="English",
        autogenerated=False,
        attempt=1,
        client="WEB",
        transcript_hash=digest,
        segments=segments,
    )

    with module.transcript_workspace(document, maximum_chunk_characters=500) as (
        directory,
        paths,
    ):
        assert directory.is_dir()
        assert paths and all(path.is_file() for path in paths)
        text = "".join(path.read_text(encoding="utf-8") for path in paths)
        assert "00:00:01.000" in text
        assert "Alpha beta" in text
        assert "Gamma & delta" in text
        retained_directory = directory

    assert not retained_directory.exists()
    assert digest == module.transcript_hash(segments)


def test_three_anonymous_attempts_end_in_terminal_unavailable(
    repository_root: Path,
) -> None:
    module = _module(repository_root)
    calls: list[str] = []

    def unavailable(_url: str, client: str) -> object:
        calls.append(client)
        raise RuntimeError("blocked")

    with pytest.raises(module.TranscriptUnavailable, match="youtube_transcript_unavailable"):
        module.extract_transcript(
            "https://www.youtube.com/watch?v=abcdefghijk",
            ["en"],
            attempts=3,
            youtube_factory=unavailable,
        )

    assert calls == ["WEB", "ANDROID", "IOS"]


def test_successful_second_client_preserves_attempt_and_canonical_hash(
    repository_root: Path,
) -> None:
    module = _module(repository_root)
    caption = Caption(
        "en",
        "English",
        [{"tStartMs": 0, "dDurationMs": 1000, "segs": [{"utf8": "One claim."}]}],
    )

    def second(_url: str, client: str) -> object:
        if client == "WEB":
            raise RuntimeError("first client unavailable")
        return Video([caption])

    document = module.extract_transcript(
        "https://www.youtube.com/watch?v=abcdefghijk",
        ["en"],
        attempts=3,
        youtube_factory=second,
    )

    assert document.attempt == 2
    assert document.client == "ANDROID"
    assert document.transcript_hash == module.transcript_hash(document.segments)
